### ISSUE TITLE
Get microservicey with Node.js, Kubernetes and gRPC

### ISSUE THREAD

**Issue by JustinBeckwith** [nodeconf/oslo#101]
The microservice architectural pattern promotes building small, single purpose services that make it  easier to build and maintain complex applications.  Deploying a ton of small services might sound hard - but Docker, Kubernetes, and gRPC make orchestrating the deployment of interconnected services easier (and dare we say fun).  In this talk we're going to cover using Docker and Kubernetes to run scalable Node.js applications across a fleet of machines.  When it's time for our services to communicate - we'll take a look at using gRPC, Google's HTTP/2 based RPC framework to enable simple communication across multiple languages.  Join us as we run through the world of node.js and microservice architecture at Google.  

**disclaimer**:  I work at Google on Node.js and Google Cloud.

**Comment by pavel-kurnosov** [comment]
I end up almost same architecture. Is there anywhere sources with examples?
