### ISSUE TITLE
Building the Perfect Beast - Robotics with Node.js

### ISSUE THREAD

**Issue by markwest1972** [nodeconf/oslo#11]
After many years in the wilderness I have recently rediscovered my love of coding.  How?  By building a Voice Controlled Robot!  In this session I will demonstrate my Robot and explain how Node.js made it all possible through the Johnny-Five framework.  Rather than focusing on specific technical details, I'll tell the story of how I got back my Coding Mojo by working on this hobby project!

My goal is to inspire others to experiment with Johnny-Five, Arduino and Raspberry PI.

**Comment by markwest1972** [comment]
In case it's interesting I have [blogged about Johnny-Five](https://utbrudd.bouvet.no/2014/12/30/learning-javascript-and-arduino-programming-with-johnny-five/).

I have also given a [similar talk at an internal work arrangement](https://www.dropbox.com/s/9s5anyaik2pkx3u/How%20I%20got%20my%20Coding%20Mojo%20Back%20-%20Mark%20West.pdf?dl=0).

**Comment by markwest1972** [comment]
Latest video of the nodebot in action : https://vimeo.com/122570460

**Comment by digitalsadhu** [comment]
Talk sounds great Mark! Your robot is looking pretty sweet in the video too!

If you are still interested in speaking, could you send me an email? (I'm struggling to find your contact details anywhere) digitalsadhu@gmail.com

Thanks!
