### ISSUE TITLE
NoFlo: Flow-based programming in node.js

### ISSUE THREAD

**Issue by jonnor** [nodeconf/oslo#12]
Hei,

I can talk around how we use node.js and [NoFlo](http://noflojs.org/), an implementation of [flow-based-progamming](http://en.wikipedia.org/wiki/Flow-based_programming), for practically all our backend infrastructure at [The Grid](https://thegrid.io/).

Also fun stuff like an [interactive table installation](http://bergie.iki.fi/blog/ingress-table/) for the Ingress virtual reality game.

**Comment by digitalsadhu** [comment]
Hey @jonnor. Are you still interested in speaking?

**Comment by jonnor** [comment]
Hi Richard,
Unfortunately I will be travelling during Nodeconf Oneshot Oslo and am not
able to attend.
