### ISSUE TITLE
We fail to follow SemVer – and why it needn’t matter

### ISSUE THREAD

**Issue by boennemann** [nodeconf/oslo#16]
Here is my proposal for the talk I'd like to give :)

> If extensive libraries and even the tiniest module followed SemVer strictly, dependency hell would be a thing of the past … but humans weren’t made to follow rules.
> 
> There are over 140.000 packages on npm today. By the time of this conference, at least another 5.000 will have been added. Using the right packages in your own modules and applications makes JavaScript the joy to develop it is today. But if even immensely popular libraries fail to properly declare breaking changes, how can we trust the over 50.000 strangers who developed all these modules?
> Currently we can’t. Let me show you how to write confidence-inspiring modules with breaking change detection and fully automated, tested releases including changelogs. Machines do a way better job with this than buggy humans.

**Comment by digitalsadhu** [comment]
Sounds pretty interesting, Thanks for the submission!

**Comment by boennemann** [comment]
@digitalsadhu Glad you like it. I'm giving this talk in Budapest the week before, just so you know. If you need anything just ask :)
