### ISSUE TITLE
Token-based authentication in REST APIs.

### ISSUE THREAD

**Issue by mewwts** [nodeconf/oslo#3]
Hey guys!

I'd like to propose a talk surrounding authenticating users in a REST API, more specifically in a Node.js server. A common issue when creating RESTful applications is authenticating the clients that connect to the API. There are several ways to handle authentication, but token-based seems to be the solution that the community is converging towards. Personally I find the token-based authentication to be almost hassle-free, especially with the node ecosystem in my back pocket.

Token-based authentication resolves around three steps. 
1. Initial authentication. This can be done with the traditional username + password and a database.
2. Handing out JSON web token that decrypts into a user-object.
3. Authenticating subsequent requests that contains an  'authorization' header containing the token.

In this talk we will go through a token-based authentication strategy involving passport.js, a JWT library(e.g. jsonwebtoken) and a datastore binding of your choice, for instance mongoose with mongodb.

Slight extensions of the talk would be storing tokens in a DB and deleting them whenever a user is deleted or logged out. It would also be interesting to visit different strategies for the initial authentication, think OAuth/OpenID/LDAP. There's the subject around attaching user information to audit logs (bunyan), which is quite simple, but useful and not straight forward. We could easily touch the subject of role-based access to routes as well. 

I'd aim to initially discuss the need of authentication, the few different approaches you might take, and why I've ended up doing things this way. Then proceed to quicky (perhaps with the help of some template code) implementing a API that does authentication, and verify it using cURL. Or even a simple web app with a login-form if we have time. 

Any further ideas? I could submit a more detailed preliminary outline of the talk if this topic is of any interest.

**Comment by sp00x** [comment]
Somehow hinting at or linking it to an RBAC layer would maybe be relevant also, although that may soon spiral into opening a huge can of worms..?

**Comment by mewwts** [comment]
Definitely, @sp00x.
If we consider only the case of limited access to routes, role-based access is quite manageable to cover in this talk. 
Thanks!

**Comment by kbrabrand** [comment]
:+1:

**Comment by mewwts** [comment]
**20 minute format revision**

This talk will be a practical walk-through of authenticating users in a node-powered REST API. We start by quickly discussing different strategies for authentication, touching cookies, sessions and tokens, OAuth, and possibly others, before we land on the following strategy: storing usernames and passwords in a database, authenticate a login request, and deliver a token that must be set in the header for each subsequent request. We will, supported by a few lines of prewritten code, implement token-based authentication, verify that it works and protects endpoints, illustrate what happens when a token expires or the app is restarted. I hope we will have time for a few questions at the end of this session.

Feel free to point out anything irrelevant or if the focus should be altered.

**Comment by digitalsadhu** [comment]
:+1:
