### ISSUE TITLE
Internet of Cats

### ISSUE THREAD

**Issue by rachelnicole** [nodeconf/oslo#39]
## Internet of Cats or, Open Source is Scary.

Ever lose out on a good nights rest because your pesky cats keep waking you up at 4am for food?? Using node, socket.io, microcontrollers, and johnny-five, I built a web based feeder that can be set to a schedule or triggered remotely. I'll walk you through my learning process with utilizing new tech for the first time and get you excited about trying your own projects so you can take the first steps to putting your work out and contributing to the open source community.

A daunting part of the OS community is the fear of scrutinization when it comes to putting your code out there for the world to see. The best part of open sourcing your own projects versus contributing to an existing library is you still get to put yourself out there and get your feet wet, but the feedback is often more positive and helpful. I want to help people that are afraid of making that first push, and enable them to go home and have the courage to experience the joy of successfully completing something open sourced for the first time.

Project on GitHub: https://github.com/rachelnicole/robokitty

![robokitty](https://github.com/rachelnicole/robokitty/raw/master/robokitty-in-action.gif)

**Comment by lrlna** [comment]
:cat: :tada: :cat: :tada: :cat:

**Comment by yoshuawuyts** [comment]
yes!
