### ISSUE TITLE
Building a non-trivial application using (only) streams and functional programming

### ISSUE THREAD

**Issue by eiriklv** [nodeconf/oslo#6]
I'm not sure what the exact outline of this talk would be (input appreciated!), but something like:

How you can build applications in node using:
- node streams
- functional javascript
- mapping/transforming (immutability)
- stream piping between processes (with backpressure)

Takeaways:
- how streams and functional javascript can be awesome
- helpful tools
- pitfalls and shortcomings of the approach

I recently built a news/article aggregator using this approach that could be the example case, and it will be open source soon.

It roughly does the following:
- aggregates news articles from the web using stream pipelines
- exposes a json and websockets API for building applications on top of

An examples of an app built on top of it can be seen at [hearsay.me](http://www.hearsay.me)

A similiar streams/fp approach (building a message/task queue) can be seen [here](https://github.com/eiriklv/process-dispatcher-worker)

**Would love some input! :-)**

**Comment by eiriklv** [comment]
I would in any case love to hear a talk about this subject - regardless of it been me or anyone else doing the actual talking.

**Comment by reminyborg** [comment]
+1 for a talk about this subject.

**Comment by eiriklv** [comment]
Application built using this approach: https://github.com/eiriklv/collectify/
